retry test

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,17 +10,17 @@ os:
 #    - os: osx
 
 python:
-  - "2.7"
+  #- "2.7"
   - "3.6"
 
 compiler:
   - gcc
 
 env:
-  - MULTINEST_TAG=v3.10 WITHMPI=mpich
-  - MULTINEST_TAG=v3.10 WITHMPI=openmpi
+  #- MULTINEST_TAG=v3.10 WITHMPI=mpich
+  #- MULTINEST_TAG=v3.10 WITHMPI=openmpi
   - MULTINEST_TAG=v3.10 WITHMPI=no
-  - MULTINEST_TAG=filelength WITHMPI=no
+  #- MULTINEST_TAG=filelength WITHMPI=no
 
 #before_install:
 #  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
@@ -117,8 +117,13 @@ script:
       if [[ "$MULTINEST_TAG" == "filelength" ]]; then
         python tests/pymultinest_long_name_test.py;
       else
-        TESTRESULT=0; python tests/pymultinest_long_name_test.py || $TESTRESULT=$?; expr $TESTRESULT != 0
-      fi
+        if python tests/pymultinest_long_name_test.py; then
+          echo "Unexpected success";
+          exit 1;
+        else
+          echo "Long name failed with error code $? as expected";
+        fi;
+      fi;
     fi
   - python multinest_marginals.py chains/3-
   - python pycuba_demo.py
